#ddev-generated
version: '3.6'
services:
  virtuoso:
    container_name: ddev-${DDEV_SITENAME}-virtuoso
    image: tenforce/virtuoso
    environment:
      SPARQL_UPDATE: 'true'
      BACKUP_PREFIX: VIRTUOSO_DUMP_
    command:
      - '/bin/bash'
      - '-c'
      - '/entrypoint.sh'
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - "./virtuoso/scripts/entrypoint.sh:/entrypoint.sh"
      - ".:/mnt/ddev_config"
